#! /bin/sh
#                                                                      
#  ▄▄                                                                   
#  ██                                                                   
#  ██▄███▄   ▄▄█████▄  ██▄███▄  ██      ██ ████▄██▄   ██▄████   ▄█████▄ 
#  ██▀  ▀██  ██▄▄▄▄ ▀  ██▀  ▀██ ▀█  ██  █▀ ██ ██ ██   ██▀      ██▀    ▀ 
#  ██    ██   ▀▀▀▀██▄  ██    ██  ██▄██▄██  ██ ██ ██   ██       ██       
#  ███▄▄██▀  █▄▄▄▄▄██  ███▄▄██▀  ▀██  ██▀  ██ ██ ██   ██       ▀██▄▄▄▄█ 
#  ▀▀ ▀▀▀     ▀▀▀▀▀▀   ██ ▀▀▀     ▀▀  ▀▀   ▀▀ ▀▀ ▀▀   ▀▀         ▀▀▀▀▀  
#                      ██                                               
#    
#                                     Config by: https://github.com/mohabaks
#

#
#  Autostart Commands
#
wallpaper=~/Pictures/bg.png

# Start things
feh --bg-fill $wallpaper &
nm-applet &
redshift &
$HOME/.config/polybar/launch_polybar.sh &

#
# Monitor & Destop Settings
# 

bspc monitor -d 1 2 3 4 5 6 7 8 9 10


#
# Global Settings
#

bspc config normal_border_color   "#000000"
bspcV config focused_border_color  "#000000"
bspc config urgent_border_color   "#000000"
bspc config presel_border_color   "#000000"

bspc config window_gap            10
bspc config border_width          5

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config click_to_focus		  true


#
#  Rule Settings
#

bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a Luakit desktop='^1' follow=on
bspc rule -a Zathura desktop='^3' state=tiled follow=on
bspc rule -a mpv desktop='^4' follow=on
bspc rule -a VirtualBox desktop='^7' follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Wireshark desktop='^8' follow=on
bspc rule -a Pcmanfm desktop='^8' follow=on
bspc rule -a burp-StartBurp desktop='^8' follow=on
bspc rule -a Gimp desktop='^8' follow=on

bspc rule -a Artha state=floating focus=on
bspc rule -a Nitrogen state=floating focus=on
bspc rule -a feh state=floating focus=on
bspc rule -a Lxappearance state=floating focus=on
