#!/usr/bin/python

import imaplib
from accounts import accounts

try:
    obj = imaplib.IMAP4_SSL('imap.gmail.com', 993)
    obj.login('otugodennis@gmail.com', 'wesley20')
    obj.select()
    mail_no = len(obj.search(None, 'UnSeen')[1][0].split())
    if mail_no == 0:
        print("No mail")
    else:
        print("{} new".format(mail_no))
except:
    pass
